version: '3'

services:
  springboot:
    container_name: spring-dev
    image: pcsbteam/pcs:latest-dev
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE : dev-env # 사용할 profile 지정
    networks:
      - pcs_network
    
networks:
  pcs_network:
    driver: bridge