spring:
  datasource:
    url: jdbc:mysql://partcross.cpbaiimaqaar.ap-northeast-2.rds.amazonaws.com:3306/partcross?useSSL=false&allowPublicKeyRetrieval=true
    username: partcross
    password: partcross
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true